---
- hosts: elasticsearch
  become: yes
  remote_user: root
  collections:
    - elkstack.ansible_collection_elk
  vars_files:
    - vars.yml

  tasks:
    - import_role:
        name: elasticsearch

- hosts: kibana 
  become: yes
  remote_user: root
  collections:
    - elkstack.ansible_collection_elk
  vars_files:
    - vars.yml

  tasks:
    - import_role:
        name: kibana

- hosts: logstash 
  become: yes
  remote_user: root
  collections:
    - elkstack.ansible_collection_elk
  vars_files:
    - vars.yml

  tasks:
    - import_role:
        name: logstash

- hosts: elasticsearch 
  become: yes
  remote_user: root
  collections:
    - elkstack.ansible_collection_elk
  vars_files:
    - vars.yml

  tasks:
    - import_role:
        name: beats
